package hosts

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderDedupesNames(t *testing.T) {
	f := New()
	f.Add("10.0.0.2", "db", "db", "database")
	f.Add("10.0.0.3", "db", "web")
	f.Add("", "ignored")
	out := f.Render()
	if strings.Count(out, "db") != 1 {
		t.Fatalf("db must appear once:\n%s", out)
	}
	if !strings.Contains(out, "10.0.0.2\tdb database") || !strings.Contains(out, "10.0.0.3\tweb") {
		t.Fatalf("unexpected render:\n%s", out)
	}
	if !strings.HasPrefix(out, "# generated by apple-compose") {
		t.Fatal("missing header")
	}
}

func TestWriteInPlaceKeepsInode(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "hosts")
	if err := Ensure(path); err != nil {
		t.Fatal(err)
	}
	before, _ := os.Stat(path)
	f := New()
	f.Add("10.0.0.2", "db")
	if err := f.Write(path); err != nil {
		t.Fatal(err)
	}
	after, _ := os.Stat(path)
	if !os.SameFile(before, after) {
		t.Fatal("Write must rewrite the same inode so bind mounts stay valid")
	}
	b, _ := os.ReadFile(path)
	if !strings.Contains(string(b), "10.0.0.2\tdb") {
		t.Fatalf("content not written: %s", b)
	}
}

func TestWritePadsToStableSize(t *testing.T) {
	path := filepath.Join(t.TempDir(), "hosts")
	f := New()
	f.Add("10.0.0.2", "db")
	if err := f.Write(path); err != nil {
		t.Fatal(err)
	}
	st, _ := os.Stat(path)
	if st.Size() != 4096 {
		t.Fatalf("first write must pad to 4096 bytes, got %d", st.Size())
	}
	b, _ := os.ReadFile(path)
	if !strings.Contains(string(b), "10.0.0.2\tdb\n") || strings.Trim(string(b[len(f.Render()):]), "\n") != "" {
		t.Fatalf("padding must be blank lines only: %q", b[len(b)-16:])
	}
	// Growing beyond one block pads to the next; shrinking keeps the size.
	big := New()
	for i := 0; i < 200; i++ {
		big.Add(fmt.Sprintf("10.0.%d.%d", i/250, i%250), fmt.Sprintf("service-%d", i), fmt.Sprintf("alias-%d", i))
	}
	if err := big.Write(path); err != nil {
		t.Fatal(err)
	}
	st, _ = os.Stat(path)
	if st.Size()%4096 != 0 || st.Size() < 8192 {
		t.Fatalf("large file must pad to a block multiple, got %d", st.Size())
	}
	grown := st.Size()
	if err := f.Write(path); err != nil {
		t.Fatal(err)
	}
	st, _ = os.Stat(path)
	if st.Size() != grown {
		t.Fatalf("a smaller rewrite must keep the size at %d, got %d", grown, st.Size())
	}
}
