// Package hosts renders the /etc/hosts files that give services their names.
//
// Apple's container runtime cannot resolve bare container names on custom
// networks, so apple-compose writes one hosts file per container and
// bind-mounts it over /etc/hosts. virtiofs propagates later rewrites into the
// running container immediately, so names can be filled in as peers start.
package hosts

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// HostGateway is the compose sentinel for the host's address in extra_hosts.
const HostGateway = "host-gateway"

// HostAliases are the names Docker Desktop publishes for the host machine.
var HostAliases = []string{"host.docker.internal", "gateway.docker.internal", "host.containers.internal"}

// Entry is one hosts line: an address and the names that resolve to it.
type Entry struct {
	IP    string
	Names []string
}

// File accumulates entries for one container.
type File struct {
	entries []Entry
	seen    map[string]bool
}

// New starts a file with the loopback line every container needs.
func New() *File {
	f := &File{seen: map[string]bool{}}
	f.Add("127.0.0.1", "localhost")
	f.Add("::1", "localhost", "ip6-localhost", "ip6-loopback")
	return f
}

// Add appends names for an address, skipping names already present so the
// first definition wins, as the resolver would treat it anyway.
func (f *File) Add(ip string, names ...string) {
	if ip == "" {
		return
	}
	var fresh []string
	for _, n := range names {
		n = strings.TrimSpace(n)
		if n == "" || f.seen[n] {
			continue
		}
		f.seen[n] = true
		fresh = append(fresh, n)
	}
	if len(fresh) == 0 {
		return
	}
	for i := range f.entries {
		if f.entries[i].IP == ip {
			f.entries[i].Names = append(f.entries[i].Names, fresh...)
			return
		}
	}
	f.entries = append(f.entries, Entry{IP: ip, Names: fresh})
}

// Render produces the file contents.
func (f *File) Render() string {
	var b strings.Builder
	b.WriteString("# generated by apple-compose; edits are overwritten\n")
	for _, e := range f.entries {
		fmt.Fprintf(&b, "%s\t%s\n", e.IP, strings.Join(e.Names, " "))
	}
	return b.String()
}

// Write rewrites path in place. The file is bind-mounted into running
// containers by inode, so it must never be replaced by rename: a renamed file
// would leave the container's mount pointing at a deleted inode.
func (f *File) Write(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(f.Render()), 0o644)
}

// Ensure creates path with the loopback line when it does not exist yet, so
// the bind mount source exists before the container is created.
func Ensure(path string) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	return New().Write(path)
}

// SortedKeys returns map keys in a stable order.
func SortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
