package hosts

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderDedupesNames(t *testing.T) {
	f := New()
	f.Add("10.0.0.2", "db", "db", "database")
	f.Add("10.0.0.3", "db", "web")
	f.Add("", "ignored")
	out := f.Render()
	if strings.Count(out, "db") != 1 {
		t.Fatalf("db must appear once:\n%s", out)
	}
	if !strings.Contains(out, "10.0.0.2\tdb database") || !strings.Contains(out, "10.0.0.3\tweb") {
		t.Fatalf("unexpected render:\n%s", out)
	}
	if !strings.HasPrefix(out, "# generated by apple-compose") {
		t.Fatal("missing header")
	}
}

func TestWriteInPlaceKeepsInode(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "hosts")
	if err := Ensure(path); err != nil {
		t.Fatal(err)
	}
	before, _ := os.Stat(path)
	f := New()
	f.Add("10.0.0.2", "db")
	if err := f.Write(path); err != nil {
		t.Fatal(err)
	}
	after, _ := os.Stat(path)
	if !os.SameFile(before, after) {
		t.Fatal("Write must rewrite the same inode so bind mounts stay valid")
	}
	b, _ := os.ReadFile(path)
	if !strings.Contains(string(b), "10.0.0.2\tdb") {
		t.Fatalf("content not written: %s", b)
	}
}
